openapi: 3.2.0
info:
  title: Swagger Petstore - OpenAPI 3.2
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.2 specification. You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS 3.2.

    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
    - [OpenAPI 3.2 Specification](https://spec.openapis.org/oas/v3.2.0.html)

  termsOfService: https://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.13
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: https://petstore32.swagger.io/api/v3
    description: Production server (OAS 3.2)
  - url: https://petstore-staging.swagger.io/api/v3
    description: Staging server
tags:
  - name: postagens
    summary: Pet management operations
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: https://swagger.io
paths:
  /postagens:
    put:
      tags:
        - postagens
      summary: Atualiza um livro.
      operationId: updateLivro
      requestBody:
        description: Atualiza um livro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Postagem'
          application/xml:
            schema:
              $ref: '#/components/schemas/Postagem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Postagem'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Postagem'
            application/xml:
              schema:
                $ref: '#/components/schemas/Postagem'
        '400':
          description: ID inválido
        '404':
          description: Livro não encontrado
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - postagens
      summary: Adiciona um novo Livro.
      operationId: addLivro
      requestBody:
        description: Cria um novo livro
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Postagem'
          application/xml:
            schema:
              $ref: '#/components/schemas/Postagem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Postagem'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Postagem'
            application/xml:
              schema:
                $ref: '#/components/schemas/Postagem'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /postagens/{id}:
    get:
      tags:
        - postagens
      summary: Seleciona um livro por id.
      operationId: getLivro
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Postagem'
            application/xml:
              schema:
                $ref: '#/components/schemas/Postagem'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - postagens
      summary: Delete user.
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Postagem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [10]
        titulo:
          type: string
          examples: ["Título de Exemplo"]
        descricao:
          type: string
          examples: ["Descrição do Item"]
        autor:
          type: string
          examples: ["Pedro Falcão"]
        dataPublicacao:
          type: string
          format: date
        fotoAutor:
          type: string
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Postagem'
        application/xml:
          schema:
            $ref: '#/components/schemas/Postagem'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Postagem'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            "write:pets": modify pets in your account
            "read:pets": read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
