openapi: 3.2.0
info:
  title: API Hands-On Programação Web
  description: |-
    Essa é uma API de teste criada como exercício na matéria de Programação Web

  termsOfService: https://swagger.io/terms/
  contact:
    email: 109990@aluno.uricer.edu.br
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.13
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: https://apihandsonprogweb.onrender.com/
tags:
  - name: postagens
paths:
  /postagens:
    put:
      tags:
        - postagens
      summary: Atualiza uma postagem.
      operationId: updatePost
      requestBody:
        description: Atualiza uma postagem
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Postagem'
          application/xml:
            schema:
              $ref: '#/components/schemas/Postagem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Postagem'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Postagem'
            application/xml:
              schema:
                $ref: '#/components/schemas/Postagem'
        '400':
          description: ID inválido
        '404':
          description: Postagem não encontrada
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      tags:
        - postagens
      summary: Adiciona uma nova postagem.
      operationId: addPost
      requestBody:
        description: Cria uma nova postagem
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Postagem'
          application/xml:
            schema:
              $ref: '#/components/schemas/Postagem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Postagem'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Postagem'
            application/xml:
              schema:
                $ref: '#/components/schemas/Postagem'
        '400':
          description: Dados inválidos
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /postagens/{id}:
    get:
      tags:
        - postagens
      summary: Seleciona uma postagem por id.
      operationId: getPost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Postagem'
            application/xml:
              schema:
                $ref: '#/components/schemas/Postagem'
        '400':
          description: ID inválido
        '404':
          description: Post não encontrad
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - postagens
      summary: Apagar postagem.
      description: Apagar uma postagem por id.
      operationId: deletePost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: ID inválido
        '404':
          description: User not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Postagem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          examples: [10]
        titulo:
          type: string
          examples: ["Título da Postagem"]
        descricao:
          type: string
          examples: ["Descrição da postagem"]
        autor:
          type: string
          examples: ["Pedro Falcão"]
        dataPublicacao:
          type: string
          format: date
        fotoAutor:
          type: string
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            "write:pets": modify pets in your account
            "read:pets": read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
